train_type_name_mapping = {
    "AKN": "AKN Eisenbahn",
    "ALX": "alex",
    "ASTB": "Autoschleuse Tauernbahn",
    "BE": "Bentheimer Eisenbahn",
    "BEX": "Bördeexpress",
    "BOB": "Bodensee-Oberschwaben-Bahn",
    "BRB": "Bayerische Regiobahn",
    "Bus": "Bus",
    "CAT": "City Airport Train",
    "CB": "CB",
    "CBG": "CBG",
    "CJX": "Cityjet xpress",
    "D": "Schnellzug",
    "DBK": "DBK",
    "DRV": "Schnellzug für Reiseveranstalter",
    "EC": "EuroCity",
    "ECE": "ECE",
    "EN": "EuroNight",
    "ENO": "ENNO",
    "ERB": "Eurobahn",
    "ES": "ES",
    "EST": "Eurostar",
    "EVB": "EVB",
    "FEX": "Flughafen-Express",
    "FLX": "Flixtrain",
    "GABW": "Arverio Baden-Württemberg",
    "GABY": "Arverio Bayern",
    "HBX": "Harz-Berlin-Express",
    "HLB": "Hessische Landesbahn",
    "HzL": "Hohenzollerische Landesbahn AG",
    "IC": "Intercity",
    "ICE": "Intercity-Express",
    "IRE": "Interregio-Express",
    "ME": "Metronom",
    "MEX": "Metropolexpress",
    "MRB": "Mitteldeutsche Regiobahn",
    "N": "N",
    "NBE": "Nordbahn Eisenbahngesellschaft",
    "NJ": "Nightjet",
    "NOB": "Nord-Ostsee-Bahn",
    "NWB": "NordWestBahn",
    "OE": "Ostdeutsche Eisenbahn",
    "OPB": "OPB",
    "R": "Regionalzug",
    "RB": "Regionalbahn",
    "RDC": "RDC",
    "RE": "Regional-Express",
    "REX": "Regional-Express",
    "RGJ": "Regiojet",
    "RJ": "Railjet",
    "RJX": "Railjet xpress",
    "RRB": "RRB",
    "RS": "Regio-S-Bahn Bremen/Niedersachsen",
    "RT": "RegioTram",
    "RTB": "Rurtalbahn GmbH",
    "S": "S-Bahn",
    "SAB": "Schwäbische Alb-Bahn",
    "SB": "Städtebahn Sachsen",
    "SBB": "Schweizerische Bundesbahnen",
    "SC": "SuperCity",
    "SE": "Städtebahn Sachsen",
    "STB": "STB",
    "STN": "STN",
    "SVG": "SVG",
    "SWE": "Südwestdeutsche Landesverkehrs-Gesellschaft",
    "TEL": "TEL",
    "TGV": "TGV",
    "TL": "TL",
    "TLX": "TLX",
    "TRI": "TRI",
    "UEX": "UEX",
    "VIA": "VIA",
    "WB": "WESTbahn",
    "WEST": "WESTbahn",
    "WFB": "Westfalenbahn",
    "ag": "ag",
    "erx": "erixX - Der Heidesprinter",
}
